# -*- coding: utf-8 -*-
"""ACNN_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blraBZ9okmrag5SRupa2OnAMk1JtIeSn
"""

!pip install -q gradio
import tensorflow as tf
import gradio as gr
import numpy as np
import cv2

model = tf.keras.models.load_model('model_9574.keras')

def classify_image(img):
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  img = cv2.resize(img, (32,32), interpolation = cv2.INTER_AREA)
  for_predicting = np.expand_dims(img, axis = 0)
  for_predicting = img.reshape(1, 32, 32, 3)
  prediction = model.predict(for_predicting)
  if prediction[0][0] > 0.5:
    label = 'Real'
  else:
    label = 'AI Generated'

  prediction = f'{(int(prediction*10000))/100}%'
  return label, prediction

gr.Interface(fn=classify_image,
             inputs=gr.Image(height = 256),
             outputs=[gr.Text(label = 'Classification'),
                      gr.Text(label = 'Probability of being a real image:')],
             examples=["seal_real.jpg", "seal_ai.jpg"],
             title = "AI Image Detector Prototype",
             description = "Sample Real Image from: https://www.pbs.org/wnet/nature/blog/seal-fact-sheet/ | Sample AI Generated Image from Meta A").launch(debug=True)

